FROM ce57c5afb395
RUN mkdir -p /opt/keycloak/certs
COPY truststore.jks /opt/keycloak/certs/
COPY keycloak.jks /opt/keycloak/certs/
#RUN chmod 777 /opt/keycloak/certs/keystore.jks
#RUN chmod 777 /opt/keycloak/certs/truststore.jks
ENV TZ="Asia/Colombo"
ENV KC_HOSTNAME_STRICT_HTTPS=true
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=mysql
#ENV KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/certs/keystore.jks
#ENV KC_HTTPS_KEY_STORE_PASSWORD=changeit
ENV KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/certs/keycloak.jks
ENV KC_HTTPS_TRUST_STORE_FILE=/opt/keycloak/certs/truststore.jks
ENV KC_HTTPS_KEY_STORE_PASSWORD=changeit
ENV KC_HTTPS_TRUST_STORE_PASSWORD=changeit
ENV KC_HOSTNAME=preprod1.fireflink.com
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
# Install custom providers
RUN /opt/keycloak/bin/kc.sh build
WORKDIR /opt/keycloak
#ENV KC_JDBC_PARAMS=sslmode=verify-full&connectTimeout=30000
ENV KC_DB_URL=jdbc:mysql://65.0.152.95:3306/keycloak?createDatabaseIfNotExist=true
ENV KC_DB=mysql
ENV KC_DATABASE_SCHEMA=public
ENV KC_DB_USERNAME=tyss
ENV KC_DB_PASSWORD=tyss
#ENV KC_HOSTNAME=preprod1.fireflink.com:8443
ENTRYPOINT ["/opt/keycloak/bin/kc.sh","start"]
